### ISSUE TITLE
cant follow chain tutorial in releases since 9.5

### ISSUE THREAD

**Issue by mfused** [runwayml/learn#58]
hi, 
this would go better in some other place, but i do not know where, as i can not report issue on main page. 
i am following this: https://learn.runwayml.com/#/how-to/chain-models-together , 
and i noticed few version before (in 9.5 that worked still) that stylegan model does not work as before, ie. there is no choice for input files (camera, files). now it is only vector z, with lot of boxes which do not load even after twenty minutes (no matter which category on the right side i choose).
thanx,
maja

**Comment by ellennickles** [comment]
Hi @mfused just following up! Are you still experiencing an issue with this tutorial?

**Comment by mfused** [comment]
All good, thanx.
